### ISSUE TITLE
Demo Readiness

### ISSUE THREAD

**Issue by EvanPiro** [EvanPiro/legiswipe-web#1]
# Tasks 

- [x] SSO Integration of either:
  - [x] Gmail 
- [x] Verdict API
  - [x] SSO identity validation
  - [x] Verdicts by user identity
- [x] Connect and collect
  - [x] Chainlink function consumer contract for token redemption
  - [x] Token redemption API
  - [x] `ethers.js` integration of front-end
- [ ] Political data market place contract
  - [ ] Chainlink function and send grid integration for offchain data exchange. 
- [x] Make the video
